---
apiVersion: v2
appVersion: latest
description: Template for one-off templates
name: app-template
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords: []
home: https://github.com/brettinternet/charts/tree/master/charts/app-template
icon: URL
sources:
  - https://github.com/brettinternet/charts/tree/master/charts/app-template
maintainers:
  - name: brett
dependencies:
  - name: app-template
    version: 0.1.1
    repository: https://bjw-s.github.io/helm-charts/
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version
